name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build-and-deploy:
    needs: go-build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Push Docker image for src
      run: |
        docker build -f Dockerfile -t src .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag src:latest ${{ secrets.DOCKER_USERNAME }}/src:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/src:latest

    - name: Build and Push Docker image for grafana
      run: |
        docker build -f grafana/Dockerfile -t grafana grafana/
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag grafana:latest ${{ secrets.DOCKER_USERNAME }}/grafana:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/grafana:latest

    - name: Build and Push Docker image for prometheus 
      run: |
        docker build -f prometheus/Dockerfile -t prometheus prometheus/
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag prometheus:latest ${{ secrets.DOCKER_USERNAME }}/prometheus:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/prometheus:latest

